@startuml

skinparam linetype ortho

actor "Desarrollador" as user
actor "Product Owner" as PO
rectangle "Git" as git
rectangle "Sonar" as sonar

rectangle build as "Development" {
  rectangle "Análisis estático de código" as static_code_analysis
  rectangle "Tets unitarios" as unit_test
}

rectangle promote_to_test as "Test" {
  rectangle "Desplegar ETL" as code_promotion_test
  rectangle "Tests de carga" as performance_test
}

rectangle promote_to_acceptance as "Acceptance" {
  rectangle "Desplegar ETL" as code_promotion_acc
}

rectangle promote_to_pro as "Production" {
  rectangle "Aprobación manual" as promotion_check
  rectangle "Desplegar ETL" as code_promotion_pro
}

rectangle "K6" as k6

user -> git : push

git --> unit_test
unit_test --> static_code_analysis
unit_test -l-> sonar
sonar -> unit_test
static_code_analysis -l-> sonar
sonar -l-> static_code_analysis

static_code_analysis -> code_promotion_test

code_promotion_test --> performance_test
performance_test --> k6
k6 -l-> performance_test
performance_test -> code_promotion_acc

code_promotion_acc -> promotion_check

promotion_check --> code_promotion_pro
PO -> promotion_check


@enduml