name: generate and commit PlantUML diagrams
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PlantUML Generator
        uses: cloudbees/plantuml-github-action@v1.1.0
