name: Build Diagrams

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PlantUML diagram generator
        uses: holowinski/plantuml-github-action@1.2021.1

