name: generate and commit PlantUML diagrams
on:
  push:
   paths:
     - "**.puml"
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PlantUML Generator
        uses: cloudbees/plantuml-github-action@v1.1.0
        with:
          args: -v -tpng ${{ steps.getfile.outputs.files }}
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "MundakaZgz"
          commit_user_email: "j.herrero.moriana@gmail.com"
          commit_author: "MundakaZgz <j.herrero.moriana@gmail.com>"
          commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
